[package]
name = "cuvs"
description = "RAPIDS vector search library"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# rapids-pre-commit-hooks: disable-next-line[verify-hardcoded-version]
ffi = { package = "cuvs-sys", path = "../cuvs-sys", version = "26.4.0" }
ndarray = "0.15"

[dev-dependencies]
ndarray-rand = "0.14"
mark-flaky-tests = "1"
