name: cuvs_cagra
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
  search: cuvs_bench.config.algos.constraints.cuvs_cagra_search
groups:
  base:
    build:
      graph_degree: [32, 64, 96, 128]
      intermediate_graph_degree: [32, 64, 96, 128]
      graph_build_algo: ["IVF_PQ"]
      compression_pq_bits: [8]
      compression_pq_dim: [384]
      compression_vq_n_centers: [1000]
    search:
      itopk: [32, 64, 128, 256, 512]
      search_width: [64]
