faiss_gpu_flat:
  executable: FAISS_GPU_FLAT_ANN_BENCH
  requires_gpu: true
faiss_gpu_ivf_flat:
  executable: FAISS_GPU_IVF_FLAT_ANN_BENCH
  requires_gpu: true
faiss_gpu_ivf_pq:
  executable: FAISS_GPU_IVF_PQ_ANN_BENCH
  requires_gpu: true
faiss_gpu_ivf_sq:
  executable: FAISS_GPU_IVF_PQ_ANN_BENCH
  requires_gpu: true
faiss_gpu_cagra:
  executable: FAISS_GPU_CAGRA_ANN_BENCH
  requires_gpu: true
faiss_gpu_cagra_hnsw:
  executable: FAISS_GPU_CAGRA_HNSW_ANN_BENCH
  requires_gpu: true
faiss_cpu_flat:
  executable: FAISS_CPU_FLAT_ANN_BENCH
  requires_gpu: false
faiss_cpu_ivf_flat:
  executable: FAISS_CPU_IVF_FLAT_ANN_BENCH
  requires_gpu: false
faiss_cpu_ivf_pq:
  executable: FAISS_CPU_IVF_PQ_ANN_BENCH
  requires_gpu: false
faiss_cpu_hnsw_flat:
  executable: FAISS_CPU_HNSW_FLAT_ANN_BENCH
  requires_gpu: false
cuvs_ivf_flat:
  executable: CUVS_IVF_FLAT_ANN_BENCH
  requires_gpu: true
cuvs_ivf_pq:
  executable: CUVS_IVF_PQ_ANN_BENCH
  requires_gpu: true
cuvs_cagra:
  executable: CUVS_CAGRA_ANN_BENCH
  requires_gpu: true
cuvs_brute_force:
  executable: CUVS_BRUTE_FORCE_ANN_BENCH
  requires_gpu: true
cuvs_mg_ivf_flat:
  executable: CUVS_MG_ANN_BENCH
  requires_gpu: true
cuvs_mg_ivf_pq:
  executable: CUVS_MG_ANN_BENCH
  requires_gpu: true
cuvs_mg_cagra:
  executable: CUVS_MG_ANN_BENCH
  requires_gpu: true
ggnn:
  executable: GGNN_ANN_BENCH
  requires_gpu: true
hnswlib:
  executable: HNSWLIB_ANN_BENCH
  requires_gpu: false
cuvs_cagra_hnswlib:
  executable: CUVS_CAGRA_HNSWLIB_ANN_BENCH
  requires_gpu: true
diskann_memory:
  executable: DISKANN_MEMORY_ANN_BENCH
  requires_gpu: false
diskann_ssd:
  executable: DISKANN_SSD_ANN_BENCH
  requires_gpu: false
cuvs_vamana:
  executable: CUVS_VAMANA_ANN_BENCH
  requires_gpu: true
cuvs_cagra_diskann:
  executable: CUVS_CAGRA_DISKANN_ANN_BENCH
  requires_gpu: true
